version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - demo
  app:
    build: . # Dockerfile
    environment:
      DATABASE_HOST: db
    ports:
      - 8080:8080
    networks:
      - demo
    depends_on:
      - db

volumes:
  mysqldata:

networks:
  demo:
    driver: bridge
